name: Run Tests
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        app_version: [stable]
        include:
          - os: ubuntu-latest
            app_version: legacy
    runs-on: ${{ matrix.os }}
    env:
      APP_VERSION: ${{ matrix.app_version }}
      VSCODE_CRASH_DIR: ${{ github.workspace }}/artifacts/dumps
      VSCODE_LOGS_DIR: ${{ github.workspace }}/artifacts/logs
      CURSORLESS_REPO_ROOT: ${{ github.workspace }}
      TEMP_DIR: ${{ github.workspace }}/temp
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: mkdir -p "${{ env.VSCODE_CRASH_DIR }}" "${{ env.VSCODE_LOGS_DIR }}" "${{ env.TEMP_DIR }}"
        shell: bash
      - run: pnpm --color install
      - run: pnpm --color compile
      - run: pnpm --color --filter '!cursorless-org' --filter '!cursorless-org-*' build
      - run: xvfb-run -a pnpm --color test
        if: runner.os == 'Linux'
      - run: pnpm --color test
        if: runner.os != 'Linux'
      - run: bash -x scripts/install-neovim-dependencies.sh
      - uses: rhysd/action-setup-vim@v1
        if: matrix.app_version != 'legacy'
        id: vim
        with:
          version: ${{ matrix.app_version }}
          neovim: true
      - name: Run neovim lua tests
        uses: ./.github/actions/run-lua-tests
        if: runner.os == 'Linux' && matrix.app_version == 'stable'
